ALTER SESSION SET CONTAINER = FREEPDB1;

SET SERVEROUTPUT ON
SET SQLBLANKLINES ON
SET DEFINE OFF
SET PAGESIZE 200
SET LINESIZE 240
SET FEEDBACK ON
SET VERIFY OFF

PROMPT
PROMPT ============================================================
PROMPT TABLA DE HALLAZGOS UNICODE
PROMPT ============================================================

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE SIGEFER_APP.UNICODE_HALLAZGO (
            ID_HALLAZGO NUMBER
                GENERATED BY DEFAULT AS IDENTITY,
            FECHA_AUDITORIA TIMESTAMP
                DEFAULT SYSTIMESTAMP NOT NULL,
            TABLA VARCHAR2(128) NOT NULL,
            COLUMNA VARCHAR2(128) NOT NULL,
            FILA_ROWID VARCHAR2(30),
            TIPO_HALLAZGO VARCHAR2(30) NOT NULL,
            VALOR_MUESTRA VARCHAR2(1000),
            VALOR_ASCII VARCHAR2(2000),

            CONSTRAINT PK_UNICODE_HALLAZGO
                PRIMARY KEY (ID_HALLAZGO)
        )
    ]';

    DBMS_OUTPUT.PUT_LINE(
        'Tabla UNICODE_HALLAZGO creada.'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE(
                'Tabla UNICODE_HALLAZGO ya existe.'
            );
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT
PROMPT ============================================================
PROMPT REPARACION DEL CATALOGO DE PRODUCTOS
PROMPT ============================================================

UPDATE SIGEFER_APP.PRODUCTO
SET NOMBRE = UNISTR(
    'Cable flexible n\00FAmero 12'
)
WHERE CODIGO = 'CABL-001';

UPDATE SIGEFER_APP.PRODUCTO
SET NOMBRE = UNISTR(
    'Pintura l\00E1tex blanca un gal\00F3n'
)
WHERE CODIGO = 'PINT-001';

UPDATE SIGEFER_APP.PRODUCTO
SET DESCRIPCION = UNISTR(
    'Casco de protecci\00F3n ajustable'
)
WHERE CODIGO = 'CASC-001';

UPDATE SIGEFER_APP.PRODUCTO
SET DESCRIPCION = UNISTR(
    'Cable de cobre para instalaciones el\00E9ctricas'
)
WHERE CODIGO = 'CABL-001';

UPDATE SIGEFER_APP.PRODUCTO
SET DESCRIPCION = UNISTR(
    'Martillo con mango ergon\00F3mico'
)
WHERE CODIGO = 'MART-001';

UPDATE SIGEFER_APP.PRODUCTO
SET DESCRIPCION = UNISTR(
    'Tornillo para fijaci\00F3n en paneles'
)
WHERE CODIGO = 'TORN-001';

UPDATE SIGEFER_APP.PRODUCTO
SET DESCRIPCION = UNISTR(
    'Taladro el\00E9ctrico para trabajo general'
)
WHERE CODIGO = 'TALA-001';

UPDATE SIGEFER_APP.PRODUCTO
SET DESCRIPCION = UNISTR(
    'Guantes de protecci\00F3n para trabajo general'
)
WHERE CODIGO = 'GUAN-001';

PROMPT
PROMPT ============================================================
PROMPT REPARACION DE CATEGORIAS
PROMPT ============================================================

UPDATE SIGEFER_APP.CATEGORIA
SET DESCRIPCION = UNISTR(
    'Tuber\00EDas y accesorios para instalaciones sanitarias'
)
WHERE ASCIISTR(DESCRIPCION) =
    'Tuber\FFFD\FFFDas y accesorios para instalaciones sanitarias';

UPDATE SIGEFER_APP.CATEGORIA
SET DESCRIPCION = UNISTR(
    'Tornillos, clavos, pernos y elementos de fijaci\00F3n'
)
WHERE ASCIISTR(DESCRIPCION) =
    'Tornillos, clavos, pernos y elementos de fijaci\FFFD\FFFDn';

UPDATE SIGEFER_APP.CATEGORIA
SET DESCRIPCION = UNISTR(
    'Equipos de protecci\00F3n personal'
)
WHERE ASCIISTR(DESCRIPCION) =
    'Equipos de protecci\FFFD\FFFDn personal';

UPDATE SIGEFER_APP.CATEGORIA
SET DESCRIPCION = UNISTR(
    'Cables y accesorios para instalaciones el\00E9ctricas'
)
WHERE ASCIISTR(DESCRIPCION) =
    'Cables y accesorios para instalaciones el\FFFD\FFFDctricas';

UPDATE SIGEFER_APP.CATEGORIA
SET DESCRIPCION = UNISTR(
    'Herramientas de operaci\00F3n manual'
)
WHERE ASCIISTR(DESCRIPCION) =
    'Herramientas de operaci\FFFD\FFFDn manual';

PROMPT
PROMPT ============================================================
PROMPT REPARACION DE CLIENTES, PROVEEDORES Y ROLES
PROMPT ============================================================

UPDATE SIGEFER_APP.CLIENTE
SET APELLIDOS = UNISTR(
    'Ram\00EDrez L\00F3pez'
)
WHERE ASCIISTR(APELLIDOS) =
    'Ram\FFFD\FFFDrez L\FFFD\FFFDpez';

UPDATE SIGEFER_APP.PROVEEDOR
SET NOMBRE_CONTACTO = UNISTR(
    'Mar\00EDa Torres'
)
WHERE ASCIISTR(NOMBRE_CONTACTO) =
    'Mar\FFFD\FFFDa Torres';

UPDATE SIGEFER_APP.ROL
SET DESCRIPCION = UNISTR(
    'Gesti\00F3n de inventario, entradas y reposici\00F3n'
)
WHERE ASCIISTR(DESCRIPCION) =
    'Gesti\FFFD\FFFDn de inventario, entradas y reposici\FFFD\FFFDn';

UPDATE SIGEFER_APP.ROL
SET DESCRIPCION = UNISTR(
    'Administraci\00F3n completa del sistema SIGEFER'
)
WHERE ASCIISTR(DESCRIPCION) =
    'Administraci\FFFD\FFFDn completa del sistema SIGEFER';

COMMIT;

PROMPT
PROMPT ============================================================
PROMPT RECREACION DE LA AUDITORIA GLOBAL
PROMPT ============================================================

TRUNCATE TABLE SIGEFER_APP.UNICODE_HALLAZGO;

DECLARE
    v_sql VARCHAR2(32767);
    v_table VARCHAR2(300);
    v_column VARCHAR2(300);
BEGIN
    FOR column_record IN (
        SELECT
            columns.TABLE_NAME,
            columns.COLUMN_NAME
        FROM ALL_TAB_COLUMNS columns
        WHERE columns.OWNER = 'SIGEFER_APP'
          AND columns.DATA_TYPE IN (
              'CHAR',
              'VARCHAR2',
              'NCHAR',
              'NVARCHAR2'
          )
          AND columns.TABLE_NAME <> 'UNICODE_HALLAZGO'
          AND EXISTS (
              SELECT 1
              FROM ALL_TABLES tables
              WHERE tables.OWNER = columns.OWNER
                AND tables.TABLE_NAME =
                    columns.TABLE_NAME
          )
        ORDER BY
            columns.TABLE_NAME,
            columns.COLUMN_ID
    ) LOOP
        v_table := DBMS_ASSERT.ENQUOTE_NAME(
            column_record.TABLE_NAME,
            FALSE
        );

        v_column := DBMS_ASSERT.ENQUOTE_NAME(
            column_record.COLUMN_NAME,
            FALSE
        );

        v_sql :=
            'INSERT INTO SIGEFER_APP.UNICODE_HALLAZGO (' ||
            'TABLA, COLUMNA, FILA_ROWID, TIPO_HALLAZGO, ' ||
            'VALOR_MUESTRA, VALOR_ASCII' ||
            ') ' ||

            'SELECT ' ||
            '''' || column_record.TABLE_NAME || ''', ' ||
            '''' || column_record.COLUMN_NAME || ''', ' ||
            'ROWIDTOCHAR(ROWID), ' ||

            'CASE ' ||
            'WHEN INSTR(' || v_column ||
            ', UNISTR(''\FFFD'')) > 0 ' ||
            'THEN ''U+FFFD'' ' ||
            'ELSE ''MOJIBAKE_POSIBLE'' ' ||
            'END, ' ||

            'SUBSTR(' || v_column || ', 1, 1000), ' ||

            'SUBSTR(' ||
            'ASCIISTR(SUBSTR(' ||
            v_column ||
            ', 1, 300)), 1, 2000) ' ||

            'FROM SIGEFER_APP.' || v_table || ' ' ||

            'WHERE ' ||
            'INSTR(' || v_column ||
            ', UNISTR(''\FFFD'')) > 0 ' ||

            'OR INSTR(' || v_column ||
            ', UNISTR(''\00C3'')) > 0 ' ||

            'OR INSTR(' || v_column ||
            ', UNISTR(''\00C2'')) > 0 ' ||

            'OR INSTR(' || v_column ||
            ', UNISTR(''\00E2'')) > 0';

        EXECUTE IMMEDIATE v_sql;
    END LOOP;

    COMMIT;
END;
/

COLUMN TABLA FORMAT A25
COLUMN COLUMNA FORMAT A25
COLUMN TIPO_HALLAZGO FORMAT A20
COLUMN VALOR_ASCII FORMAT A120

PROMPT
PROMPT ============================================================
PROMPT HALLAZGOS RESTANTES
PROMPT ============================================================

SELECT
    TABLA,
    COLUMNA,
    TIPO_HALLAZGO,
    VALOR_ASCII
FROM SIGEFER_APP.UNICODE_HALLAZGO
ORDER BY
    TABLA,
    COLUMNA,
    ID_HALLAZGO;

PROMPT
PROMPT ============================================================
PROMPT TOTAL DE HALLAZGOS
PROMPT ============================================================

SELECT
    COUNT(*) AS TOTAL_HALLAZGOS
FROM SIGEFER_APP.UNICODE_HALLAZGO;

PROMPT
PROMPT ============================================================
PROMPT VERIFICACION DE TEXTOS REPARADOS
PROMPT ============================================================

SELECT
    CODIGO,
    ASCIISTR(NOMBRE) AS NOMBRE_ASCII,
    ASCIISTR(DESCRIPCION) AS DESCRIPCION_ASCII
FROM SIGEFER_APP.PRODUCTO
WHERE CODIGO IN (
    'CABL-001',
    'PINT-001',
    'MART-001',
    'TALA-001',
    'TORN-001',
    'GUAN-001',
    'CASC-001'
)
ORDER BY CODIGO;

EXIT;
