ALTER SESSION SET CONTAINER = FREEPDB1;

SET SERVEROUTPUT ON
SET SQLBLANKLINES ON
SET FEEDBACK ON
SET VERIFY OFF

PROMPT
PROMPT ============================================================
PROMPT AMPLIACION DE USUARIO PARA CONTROL DE BLOQUEOS
PROMPT ============================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'SIGEFER_APP'
      AND TABLE_NAME = 'USUARIO'
      AND COLUMN_NAME = 'ULTIMO_INTENTO_FALLIDO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE SIGEFER_APP.USUARIO
            ADD ULTIMO_INTENTO_FALLIDO TIMESTAMP(6)
        ';

        DBMS_OUTPUT.PUT_LINE(
            'Columna ULTIMO_INTENTO_FALLIDO creada.'
        );
    END IF;

    SELECT COUNT(*)
    INTO v_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'SIGEFER_APP'
      AND TABLE_NAME = 'USUARIO'
      AND COLUMN_NAME = 'FECHA_BLOQUEO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE SIGEFER_APP.USUARIO
            ADD FECHA_BLOQUEO TIMESTAMP(6)
        ';

        DBMS_OUTPUT.PUT_LINE(
            'Columna FECHA_BLOQUEO creada.'
        );
    END IF;
END;
/

PROMPT
PROMPT ============================================================
PROMPT TABLA DE SESIONES
PROMPT ============================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_TABLES
    WHERE OWNER = 'SIGEFER_APP'
      AND TABLE_NAME = 'SESION_USUARIO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SIGEFER_APP.SESION_USUARIO (
                ID_SESION NUMBER
                    GENERATED BY DEFAULT AS IDENTITY,

                ID_USUARIO NUMBER NOT NULL,

                TOKEN_HASH VARCHAR2(64) NOT NULL,

                FECHA_CREACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                FECHA_EXPIRACION TIMESTAMP(6) NOT NULL,

                FECHA_REVOCACION TIMESTAMP(6),

                ULTIMA_ACTIVIDAD TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                IP_ORIGEN VARCHAR2(50),

                AGENTE_USUARIO VARCHAR2(500),

                CONSTRAINT PK_SESION_USUARIO
                    PRIMARY KEY (ID_SESION),

                CONSTRAINT FK_SESION_USUARIO
                    FOREIGN KEY (ID_USUARIO)
                    REFERENCES SIGEFER_APP.USUARIO (
                        ID_USUARIO
                    ),

                CONSTRAINT UQ_SESION_TOKEN_HASH
                    UNIQUE (TOKEN_HASH),

                CONSTRAINT CK_SESION_FECHAS
                    CHECK (
                        FECHA_EXPIRACION >
                        FECHA_CREACION
                    ),

                CONSTRAINT CK_SESION_REVOCACION
                    CHECK (
                        FECHA_REVOCACION IS NULL
                        OR FECHA_REVOCACION >=
                            FECHA_CREACION
                    ),

                CONSTRAINT CKU_SESION_TOKEN_HASH
                    CHECK (
                        INSTR(
                            TOKEN_HASH,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_SESION_IP
                    CHECK (
                        IP_ORIGEN IS NULL
                        OR INSTR(
                            IP_ORIGEN,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_SESION_AGENTE
                    CHECK (
                        AGENTE_USUARIO IS NULL
                        OR INSTR(
                            AGENTE_USUARIO,
                            UNISTR('\FFFD')
                        ) = 0
                    )
            )
        ]';

        DBMS_OUTPUT.PUT_LINE(
            'Tabla SESION_USUARIO creada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'Tabla SESION_USUARIO ya existe.'
        );
    END IF;
END;
/

PROMPT
PROMPT ============================================================
PROMPT INDICES DE SESIONES
PROMPT ============================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_INDEXES
    WHERE OWNER = 'SIGEFER_APP'
      AND INDEX_NAME = 'IX_SESION_USUARIO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX
                SIGEFER_APP.IX_SESION_USUARIO
            ON SIGEFER_APP.SESION_USUARIO (
                ID_USUARIO
            )
        ';
    END IF;

    SELECT COUNT(*)
    INTO v_count
    FROM ALL_INDEXES
    WHERE OWNER = 'SIGEFER_APP'
      AND INDEX_NAME = 'IX_SESION_EXPIRACION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX
                SIGEFER_APP.IX_SESION_EXPIRACION
            ON SIGEFER_APP.SESION_USUARIO (
                FECHA_EXPIRACION,
                FECHA_REVOCACION
            )
        ';
    END IF;
END;
/

PROMPT
PROMPT ============================================================
PROMPT VERIFICACION
PROMPT ============================================================

COLUMN COLUMN_NAME FORMAT A30
COLUMN DATA_TYPE FORMAT A22
COLUMN NULLABLE FORMAT A10
COLUMN CONSTRAINT_NAME FORMAT A35
COLUMN STATUS FORMAT A10

SELECT
    COLUMN_ID,
    COLUMN_NAME,
    DATA_TYPE,
    NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME = 'SESION_USUARIO'
ORDER BY COLUMN_ID;

SELECT
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    STATUS
FROM ALL_CONSTRAINTS
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME = 'SESION_USUARIO'
ORDER BY CONSTRAINT_NAME;

EXIT;
