ALTER SESSION SET CONTAINER = FREEPDB1;

SET SERVEROUTPUT ON
SET SQLBLANKLINES ON
SET FEEDBACK ON
SET VERIFY OFF
SET PAGESIZE 200
SET LINESIZE 260

PROMPT
PROMPT ============================================================
PROMPT 1. SECUENCIA PARA NUMEROS DE REPOSICION
PROMPT ============================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_SEQUENCES
    WHERE SEQUENCE_OWNER = 'SIGEFER_APP'
      AND SEQUENCE_NAME = 'SEQ_NUM_REPOSICION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE SEQUENCE SIGEFER_APP.SEQ_NUM_REPOSICION
            START WITH 1
            INCREMENT BY 1
            NOCACHE
            NOCYCLE
        ';

        DBMS_OUTPUT.PUT_LINE(
            'Secuencia SEQ_NUM_REPOSICION creada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'Secuencia SEQ_NUM_REPOSICION ya existe.'
        );
    END IF;
END;
/

PROMPT
PROMPT ============================================================
PROMPT 2. TABLA SOLICITUD_REPOSICION
PROMPT ============================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_TABLES
    WHERE OWNER = 'SIGEFER_APP'
      AND TABLE_NAME = 'SOLICITUD_REPOSICION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SIGEFER_APP.SOLICITUD_REPOSICION (
                ID_SOLICITUD NUMBER
                    GENERATED BY DEFAULT AS IDENTITY,

                NUMERO_SOLICITUD VARCHAR2(30) NOT NULL,

                ID_PRODUCTO NUMBER NOT NULL,

                ID_PROVEEDOR NUMBER NOT NULL,

                ID_ALERTA NUMBER,

                CANTIDAD_SOLICITADA NUMBER(14,3)
                    NOT NULL,

                CANTIDAD_RECIBIDA NUMBER(14,3)
                    DEFAULT 0 NOT NULL,

                COSTO_UNITARIO_ESTIMADO NUMBER(14,2)
                    NOT NULL,

                COSTO_TOTAL_ESTIMADO
                    GENERATED ALWAYS AS (
                        ROUND(
                            CANTIDAD_SOLICITADA
                            * COSTO_UNITARIO_ESTIMADO,
                            2
                        )
                    ) VIRTUAL,

                ESTADO VARCHAR2(15)
                    DEFAULT 'BORRADOR' NOT NULL,

                ID_USUARIO_SOLICITANTE NUMBER NOT NULL,

                ID_USUARIO_APROBADOR NUMBER,

                ID_USUARIO_RECEPTOR NUMBER,

                FECHA_SOLICITUD TIMESTAMP(6),

                FECHA_APROBACION TIMESTAMP(6),

                FECHA_RECHAZO TIMESTAMP(6),

                FECHA_PEDIDO TIMESTAMP(6),

                FECHA_RECEPCION TIMESTAMP(6),

                FECHA_CIERRE TIMESTAMP(6),

                OBSERVACION VARCHAR2(1000),

                MOTIVO_RECHAZO VARCHAR2(500),

                FECHA_CREACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                FECHA_ACTUALIZACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                CONSTRAINT PK_SOLICITUD_REPOSICION
                    PRIMARY KEY (ID_SOLICITUD),

                CONSTRAINT UQ_REP_NUMERO
                    UNIQUE (NUMERO_SOLICITUD),

                CONSTRAINT FK_REP_PRODUCTO
                    FOREIGN KEY (ID_PRODUCTO)
                    REFERENCES SIGEFER_APP.PRODUCTO (
                        ID_PRODUCTO
                    ),

                CONSTRAINT FK_REP_PROVEEDOR
                    FOREIGN KEY (ID_PROVEEDOR)
                    REFERENCES SIGEFER_APP.PROVEEDOR (
                        ID_PROVEEDOR
                    ),

                CONSTRAINT FK_REP_ALERTA
                    FOREIGN KEY (ID_ALERTA)
                    REFERENCES SIGEFER_APP.ALERTA_STOCK (
                        ID_ALERTA
                    ),

                CONSTRAINT FK_REP_USU_SOL
                    FOREIGN KEY (
                        ID_USUARIO_SOLICITANTE
                    )
                    REFERENCES SIGEFER_APP.USUARIO (
                        ID_USUARIO
                    ),

                CONSTRAINT FK_REP_USU_APR
                    FOREIGN KEY (
                        ID_USUARIO_APROBADOR
                    )
                    REFERENCES SIGEFER_APP.USUARIO (
                        ID_USUARIO
                    ),

                CONSTRAINT FK_REP_USU_REC
                    FOREIGN KEY (
                        ID_USUARIO_RECEPTOR
                    )
                    REFERENCES SIGEFER_APP.USUARIO (
                        ID_USUARIO
                    ),

                CONSTRAINT CK_REP_CANT_SOL
                    CHECK (
                        CANTIDAD_SOLICITADA > 0
                    ),

                CONSTRAINT CK_REP_CANT_REC
                    CHECK (
                        CANTIDAD_RECIBIDA >= 0
                        AND CANTIDAD_RECIBIDA
                            <= CANTIDAD_SOLICITADA
                    ),

                CONSTRAINT CK_REP_COSTO_EST
                    CHECK (
                        COSTO_UNITARIO_ESTIMADO >= 0
                    ),

                CONSTRAINT CK_REP_ESTADO
                    CHECK (
                        ESTADO IN (
                            'BORRADOR',
                            'SOLICITADA',
                            'APROBADA',
                            'RECHAZADA',
                            'EN_PEDIDO',
                            'RECIBIDA',
                            'CERRADA'
                        )
                    ),

                CONSTRAINT CK_REP_FECHAS
                    CHECK (
                        (
                            FECHA_SOLICITUD IS NULL
                            OR FECHA_SOLICITUD
                                >= FECHA_CREACION
                        )
                        AND (
                            FECHA_APROBACION IS NULL
                            OR FECHA_APROBACION
                                >= FECHA_SOLICITUD
                        )
                        AND (
                            FECHA_RECHAZO IS NULL
                            OR FECHA_RECHAZO
                                >= FECHA_SOLICITUD
                        )
                        AND (
                            FECHA_PEDIDO IS NULL
                            OR FECHA_PEDIDO
                                >= FECHA_APROBACION
                        )
                        AND (
                            FECHA_RECEPCION IS NULL
                            OR FECHA_RECEPCION
                                >= FECHA_PEDIDO
                        )
                        AND (
                            FECHA_CIERRE IS NULL
                            OR FECHA_CIERRE
                                >= FECHA_RECEPCION
                        )
                    ),

                CONSTRAINT CK_REP_ESTADO_FECHAS
                    CHECK (
                        (
                            ESTADO = 'BORRADOR'
                            AND FECHA_SOLICITUD IS NULL
                            AND FECHA_APROBACION IS NULL
                            AND FECHA_RECHAZO IS NULL
                            AND FECHA_PEDIDO IS NULL
                            AND FECHA_RECEPCION IS NULL
                            AND FECHA_CIERRE IS NULL
                            AND CANTIDAD_RECIBIDA = 0
                        )
                        OR
                        (
                            ESTADO = 'SOLICITADA'
                            AND FECHA_SOLICITUD IS NOT NULL
                            AND FECHA_APROBACION IS NULL
                            AND FECHA_RECHAZO IS NULL
                            AND FECHA_PEDIDO IS NULL
                            AND FECHA_RECEPCION IS NULL
                            AND FECHA_CIERRE IS NULL
                            AND CANTIDAD_RECIBIDA = 0
                        )
                        OR
                        (
                            ESTADO = 'APROBADA'
                            AND FECHA_SOLICITUD IS NOT NULL
                            AND FECHA_APROBACION IS NOT NULL
                            AND ID_USUARIO_APROBADOR
                                IS NOT NULL
                            AND FECHA_RECHAZO IS NULL
                            AND FECHA_PEDIDO IS NULL
                            AND FECHA_RECEPCION IS NULL
                            AND FECHA_CIERRE IS NULL
                            AND CANTIDAD_RECIBIDA = 0
                        )
                        OR
                        (
                            ESTADO = 'RECHAZADA'
                            AND FECHA_SOLICITUD IS NOT NULL
                            AND FECHA_RECHAZO IS NOT NULL
                            AND ID_USUARIO_APROBADOR
                                IS NOT NULL
                            AND MOTIVO_RECHAZO IS NOT NULL
                            AND FECHA_APROBACION IS NULL
                            AND FECHA_PEDIDO IS NULL
                            AND FECHA_RECEPCION IS NULL
                            AND FECHA_CIERRE IS NULL
                            AND CANTIDAD_RECIBIDA = 0
                        )
                        OR
                        (
                            ESTADO = 'EN_PEDIDO'
                            AND FECHA_SOLICITUD IS NOT NULL
                            AND FECHA_APROBACION IS NOT NULL
                            AND FECHA_PEDIDO IS NOT NULL
                            AND ID_USUARIO_APROBADOR
                                IS NOT NULL
                            AND FECHA_RECHAZO IS NULL
                            AND FECHA_RECEPCION IS NULL
                            AND FECHA_CIERRE IS NULL
                            AND CANTIDAD_RECIBIDA = 0
                        )
                        OR
                        (
                            ESTADO = 'RECIBIDA'
                            AND FECHA_SOLICITUD IS NOT NULL
                            AND FECHA_APROBACION IS NOT NULL
                            AND FECHA_PEDIDO IS NOT NULL
                            AND FECHA_RECEPCION IS NOT NULL
                            AND ID_USUARIO_APROBADOR
                                IS NOT NULL
                            AND ID_USUARIO_RECEPTOR
                                IS NOT NULL
                            AND FECHA_RECHAZO IS NULL
                            AND FECHA_CIERRE IS NULL
                            AND CANTIDAD_RECIBIDA > 0
                        )
                        OR
                        (
                            ESTADO = 'CERRADA'
                            AND FECHA_SOLICITUD IS NOT NULL
                            AND FECHA_APROBACION IS NOT NULL
                            AND FECHA_PEDIDO IS NOT NULL
                            AND FECHA_RECEPCION IS NOT NULL
                            AND FECHA_CIERRE IS NOT NULL
                            AND ID_USUARIO_APROBADOR
                                IS NOT NULL
                            AND ID_USUARIO_RECEPTOR
                                IS NOT NULL
                            AND FECHA_RECHAZO IS NULL
                            AND CANTIDAD_RECIBIDA > 0
                        )
                    ),

                CONSTRAINT CKU_REP_NUMERO
                    CHECK (
                        INSTR(
                            NUMERO_SOLICITUD,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_REP_ESTADO
                    CHECK (
                        INSTR(
                            ESTADO,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_REP_OBSERVACION
                    CHECK (
                        OBSERVACION IS NULL
                        OR INSTR(
                            OBSERVACION,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_REP_MOT_RECHAZO
                    CHECK (
                        MOTIVO_RECHAZO IS NULL
                        OR INSTR(
                            MOTIVO_RECHAZO,
                            UNISTR('\FFFD')
                        ) = 0
                    )
            )
        ]';

        DBMS_OUTPUT.PUT_LINE(
            'Tabla SOLICITUD_REPOSICION creada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'Tabla SOLICITUD_REPOSICION ya existe.'
        );
    END IF;
END;
/

COMMENT ON TABLE SIGEFER_APP.SOLICITUD_REPOSICION IS
'Instancias del proceso BPM de reposicion de inventario';

COMMENT ON COLUMN
SIGEFER_APP.SOLICITUD_REPOSICION.ID_ALERTA IS
'Alerta de stock que origino la solicitud, cuando aplica';

COMMENT ON COLUMN
SIGEFER_APP.SOLICITUD_REPOSICION.ID_USUARIO_APROBADOR IS
'Usuario que aprueba o rechaza la solicitud';

PROMPT
PROMPT ============================================================
PROMPT 3. INDICES DE SOLICITUD_REPOSICION
PROMPT ============================================================

DECLARE
    PROCEDURE create_index_if_missing(
        p_index_name VARCHAR2,
        p_statement  VARCHAR2
    ) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM ALL_INDEXES
        WHERE OWNER = 'SIGEFER_APP'
          AND INDEX_NAME = p_index_name;

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_statement;

            DBMS_OUTPUT.PUT_LINE(
                'Indice ' || p_index_name || ' creado.'
            );
        END IF;
    END;
BEGIN
    create_index_if_missing(
        'IX_REP_PRODUCTO',
        'CREATE INDEX SIGEFER_APP.IX_REP_PRODUCTO
         ON SIGEFER_APP.SOLICITUD_REPOSICION (
             ID_PRODUCTO
         )'
    );

    create_index_if_missing(
        'IX_REP_PROVEEDOR',
        'CREATE INDEX SIGEFER_APP.IX_REP_PROVEEDOR
         ON SIGEFER_APP.SOLICITUD_REPOSICION (
             ID_PROVEEDOR
         )'
    );

    create_index_if_missing(
        'IX_REP_ALERTA',
        'CREATE INDEX SIGEFER_APP.IX_REP_ALERTA
         ON SIGEFER_APP.SOLICITUD_REPOSICION (
             ID_ALERTA
         )'
    );

    create_index_if_missing(
        'IX_REP_ESTADO',
        'CREATE INDEX SIGEFER_APP.IX_REP_ESTADO
         ON SIGEFER_APP.SOLICITUD_REPOSICION (
             ESTADO
         )'
    );

    create_index_if_missing(
        'IX_REP_FECHA_SOL',
        'CREATE INDEX SIGEFER_APP.IX_REP_FECHA_SOL
         ON SIGEFER_APP.SOLICITUD_REPOSICION (
             FECHA_SOLICITUD
         )'
    );

    create_index_if_missing(
        'IX_REP_USU_SOL',
        'CREATE INDEX SIGEFER_APP.IX_REP_USU_SOL
         ON SIGEFER_APP.SOLICITUD_REPOSICION (
             ID_USUARIO_SOLICITANTE
         )'
    );

    create_index_if_missing(
        'IX_REP_USU_APR',
        'CREATE INDEX SIGEFER_APP.IX_REP_USU_APR
         ON SIGEFER_APP.SOLICITUD_REPOSICION (
             ID_USUARIO_APROBADOR
         )'
    );

    create_index_if_missing(
        'IX_REP_USU_REC',
        'CREATE INDEX SIGEFER_APP.IX_REP_USU_REC
         ON SIGEFER_APP.SOLICITUD_REPOSICION (
             ID_USUARIO_RECEPTOR
         )'
    );

    create_index_if_missing(
        'UQ_REP_PRODUCTO_ACTIVA',
        q'[
            CREATE UNIQUE INDEX
                SIGEFER_APP.UQ_REP_PRODUCTO_ACTIVA
            ON SIGEFER_APP.SOLICITUD_REPOSICION (
                CASE
                    WHEN ESTADO IN (
                        'BORRADOR',
                        'SOLICITADA',
                        'APROBADA',
                        'EN_PEDIDO',
                        'RECIBIDA'
                    )
                    THEN ID_PRODUCTO
                END
            )
        ]'
    );
END;
/

PROMPT
PROMPT ============================================================
PROMPT 4. TABLA HISTORIAL_REPOSICION
PROMPT ============================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_TABLES
    WHERE OWNER = 'SIGEFER_APP'
      AND TABLE_NAME = 'HISTORIAL_REPOSICION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SIGEFER_APP.HISTORIAL_REPOSICION (
                ID_HISTORIAL NUMBER
                    GENERATED BY DEFAULT AS IDENTITY,

                ID_SOLICITUD NUMBER NOT NULL,

                ID_USUARIO NUMBER NOT NULL,

                ESTADO_ANTERIOR VARCHAR2(15),

                ESTADO_NUEVO VARCHAR2(15) NOT NULL,

                ACCION VARCHAR2(30) NOT NULL,

                OBSERVACION VARCHAR2(1000),

                FECHA_EVENTO TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                CONSTRAINT PK_HISTORIAL_REPOSICION
                    PRIMARY KEY (ID_HISTORIAL),

                CONSTRAINT FK_HREP_SOLICITUD
                    FOREIGN KEY (ID_SOLICITUD)
                    REFERENCES
                        SIGEFER_APP.SOLICITUD_REPOSICION (
                            ID_SOLICITUD
                        ),

                CONSTRAINT FK_HREP_USUARIO
                    FOREIGN KEY (ID_USUARIO)
                    REFERENCES SIGEFER_APP.USUARIO (
                        ID_USUARIO
                    ),

                CONSTRAINT CK_HREP_EST_ANT
                    CHECK (
                        ESTADO_ANTERIOR IS NULL
                        OR ESTADO_ANTERIOR IN (
                            'BORRADOR',
                            'SOLICITADA',
                            'APROBADA',
                            'RECHAZADA',
                            'EN_PEDIDO',
                            'RECIBIDA',
                            'CERRADA'
                        )
                    ),

                CONSTRAINT CK_HREP_EST_NUE
                    CHECK (
                        ESTADO_NUEVO IN (
                            'BORRADOR',
                            'SOLICITADA',
                            'APROBADA',
                            'RECHAZADA',
                            'EN_PEDIDO',
                            'RECIBIDA',
                            'CERRADA'
                        )
                    ),

                CONSTRAINT CK_HREP_ACCION
                    CHECK (
                        ACCION IN (
                            'CREAR',
                            'ENVIAR',
                            'APROBAR',
                            'RECHAZAR',
                            'MARCAR_PEDIDO',
                            'RECIBIR',
                            'CERRAR'
                        )
                    ),

                CONSTRAINT CKU_HREP_EST_ANT
                    CHECK (
                        ESTADO_ANTERIOR IS NULL
                        OR INSTR(
                            ESTADO_ANTERIOR,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_HREP_EST_NUE
                    CHECK (
                        INSTR(
                            ESTADO_NUEVO,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_HREP_ACCION
                    CHECK (
                        INSTR(
                            ACCION,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_HREP_OBSERVACION
                    CHECK (
                        OBSERVACION IS NULL
                        OR INSTR(
                            OBSERVACION,
                            UNISTR('\FFFD')
                        ) = 0
                    )
            )
        ]';

        DBMS_OUTPUT.PUT_LINE(
            'Tabla HISTORIAL_REPOSICION creada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'Tabla HISTORIAL_REPOSICION ya existe.'
        );
    END IF;
END;
/

COMMENT ON TABLE SIGEFER_APP.HISTORIAL_REPOSICION IS
'Historial inmutable de transiciones del proceso de reposicion';

PROMPT
PROMPT ============================================================
PROMPT 5. INDICES DE HISTORIAL
PROMPT ============================================================

DECLARE
    PROCEDURE create_index_if_missing(
        p_index_name VARCHAR2,
        p_statement  VARCHAR2
    ) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM ALL_INDEXES
        WHERE OWNER = 'SIGEFER_APP'
          AND INDEX_NAME = p_index_name;

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_statement;
        END IF;
    END;
BEGIN
    create_index_if_missing(
        'IX_HREP_SOLICITUD',
        'CREATE INDEX SIGEFER_APP.IX_HREP_SOLICITUD
         ON SIGEFER_APP.HISTORIAL_REPOSICION (
             ID_SOLICITUD,
             FECHA_EVENTO
         )'
    );

    create_index_if_missing(
        'IX_HREP_USUARIO',
        'CREATE INDEX SIGEFER_APP.IX_HREP_USUARIO
         ON SIGEFER_APP.HISTORIAL_REPOSICION (
             ID_USUARIO
         )'
    );

    create_index_if_missing(
        'IX_HREP_FECHA',
        'CREATE INDEX SIGEFER_APP.IX_HREP_FECHA
         ON SIGEFER_APP.HISTORIAL_REPOSICION (
             FECHA_EVENTO
         )'
    );
END;
/

PROMPT
PROMPT ============================================================
PROMPT 6. TRAZABILIDAD EN MOVIMIENTO_INVENTARIO
PROMPT ============================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'SIGEFER_APP'
      AND TABLE_NAME = 'MOVIMIENTO_INVENTARIO'
      AND COLUMN_NAME = 'ID_SOLICITUD_REPOSICION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE
                SIGEFER_APP.MOVIMIENTO_INVENTARIO
            ADD ID_SOLICITUD_REPOSICION NUMBER
        ';

        DBMS_OUTPUT.PUT_LINE(
            'Columna ID_SOLICITUD_REPOSICION creada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'Columna ID_SOLICITUD_REPOSICION ya existe.'
        );
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_CONSTRAINTS
    WHERE OWNER = 'SIGEFER_APP'
      AND CONSTRAINT_NAME =
          'FK_MOVIMIENTO_REPOSICION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE
                SIGEFER_APP.MOVIMIENTO_INVENTARIO
            ADD CONSTRAINT FK_MOVIMIENTO_REPOSICION
                FOREIGN KEY (
                    ID_SOLICITUD_REPOSICION
                )
                REFERENCES
                    SIGEFER_APP.SOLICITUD_REPOSICION (
                        ID_SOLICITUD
                    )
        ';
    END IF;

    SELECT COUNT(*)
    INTO v_count
    FROM ALL_CONSTRAINTS
    WHERE OWNER = 'SIGEFER_APP'
      AND CONSTRAINT_NAME =
          'CK_MOVIMIENTO_REPOSICION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE
                SIGEFER_APP.MOVIMIENTO_INVENTARIO
            ADD CONSTRAINT CK_MOVIMIENTO_REPOSICION
            CHECK (
                (
                    TIPO_MOVIMIENTO = 'ENTRADA_COMPRA'
                    AND ID_SOLICITUD_REPOSICION
                        IS NOT NULL
                )
                OR
                (
                    TIPO_MOVIMIENTO <> 'ENTRADA_COMPRA'
                    AND ID_SOLICITUD_REPOSICION
                        IS NULL
                )
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_INDEXES
    WHERE OWNER = 'SIGEFER_APP'
      AND INDEX_NAME = 'IX_MOV_REPOSICION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX
                SIGEFER_APP.IX_MOV_REPOSICION
            ON SIGEFER_APP.MOVIMIENTO_INVENTARIO (
                ID_SOLICITUD_REPOSICION
            )
        ';
    END IF;
END;
/

PROMPT
PROMPT ============================================================
PROMPT 7. VISTA GERENCIAL BPM
PROMPT ============================================================

CREATE OR REPLACE VIEW SIGEFER_APP.VW_BPM_REPOSICION AS
SELECT
    solicitud.ID_SOLICITUD,
    solicitud.NUMERO_SOLICITUD,

    solicitud.ID_PRODUCTO,
    producto.CODIGO AS CODIGO_PRODUCTO,
    producto.NOMBRE AS PRODUCTO,
    producto.UNIDAD_MEDIDA,

    solicitud.ID_PROVEEDOR,
    proveedor.RUC AS RUC_PROVEEDOR,
    proveedor.RAZON_SOCIAL AS PROVEEDOR,

    solicitud.ID_ALERTA,
    alerta.TIPO_ALERTA,
    alerta.ESTADO AS ESTADO_ALERTA,

    solicitud.CANTIDAD_SOLICITADA,
    solicitud.CANTIDAD_RECIBIDA,

    solicitud.COSTO_UNITARIO_ESTIMADO,
    solicitud.COSTO_TOTAL_ESTIMADO,

    solicitud.ESTADO,

    inventario.STOCK_ACTUAL,
    inventario.STOCK_RESERVADO,
    inventario.STOCK_DISPONIBLE,
    producto.STOCK_MINIMO,

    solicitud.ID_USUARIO_SOLICITANTE,
    usuario_solicitante.NOMBRE_USUARIO
        AS USUARIO_SOLICITANTE,

    solicitud.ID_USUARIO_APROBADOR,
    usuario_aprobador.NOMBRE_USUARIO
        AS USUARIO_APROBADOR,

    solicitud.ID_USUARIO_RECEPTOR,
    usuario_receptor.NOMBRE_USUARIO
        AS USUARIO_RECEPTOR,

    solicitud.FECHA_SOLICITUD,
    solicitud.FECHA_APROBACION,
    solicitud.FECHA_RECHAZO,
    solicitud.FECHA_PEDIDO,
    solicitud.FECHA_RECEPCION,
    solicitud.FECHA_CIERRE,

    solicitud.OBSERVACION,
    solicitud.MOTIVO_RECHAZO,

    solicitud.FECHA_CREACION,
    solicitud.FECHA_ACTUALIZACION

FROM SIGEFER_APP.SOLICITUD_REPOSICION solicitud

INNER JOIN SIGEFER_APP.PRODUCTO producto
    ON producto.ID_PRODUCTO =
        solicitud.ID_PRODUCTO

INNER JOIN SIGEFER_APP.PROVEEDOR proveedor
    ON proveedor.ID_PROVEEDOR =
        solicitud.ID_PROVEEDOR

INNER JOIN SIGEFER_APP.INVENTARIO inventario
    ON inventario.ID_PRODUCTO =
        solicitud.ID_PRODUCTO

INNER JOIN SIGEFER_APP.USUARIO usuario_solicitante
    ON usuario_solicitante.ID_USUARIO =
        solicitud.ID_USUARIO_SOLICITANTE

LEFT JOIN SIGEFER_APP.USUARIO usuario_aprobador
    ON usuario_aprobador.ID_USUARIO =
        solicitud.ID_USUARIO_APROBADOR

LEFT JOIN SIGEFER_APP.USUARIO usuario_receptor
    ON usuario_receptor.ID_USUARIO =
        solicitud.ID_USUARIO_RECEPTOR

LEFT JOIN SIGEFER_APP.ALERTA_STOCK alerta
    ON alerta.ID_ALERTA =
        solicitud.ID_ALERTA;

COMMENT ON TABLE SIGEFER_APP.VW_BPM_REPOSICION IS
'Vista consolidada del proceso BPM de reposicion';

PROMPT
PROMPT ============================================================
PROMPT 8. VERIFICACION
PROMPT ============================================================

COLUMN TABLE_NAME FORMAT A32
COLUMN COLUMN_NAME FORMAT A32
COLUMN CONSTRAINT_NAME FORMAT A35
COLUMN INDEX_NAME FORMAT A35
COLUMN STATUS FORMAT A10

SELECT
    TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME IN (
      'SOLICITUD_REPOSICION',
      'HISTORIAL_REPOSICION'
  )
ORDER BY TABLE_NAME;

SELECT
    TABLE_NAME,
    COUNT(*) AS TOTAL_COLUMNAS
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME IN (
      'SOLICITUD_REPOSICION',
      'HISTORIAL_REPOSICION'
  )
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

SELECT
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    STATUS
FROM ALL_CONSTRAINTS
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME IN (
      'SOLICITUD_REPOSICION',
      'HISTORIAL_REPOSICION',
      'MOVIMIENTO_INVENTARIO'
  )
  AND (
      CONSTRAINT_NAME LIKE '%REP%'
      OR CONSTRAINT_NAME LIKE '%REPOSICION%'
  )
ORDER BY CONSTRAINT_NAME;

SELECT
    INDEX_NAME,
    STATUS
FROM ALL_INDEXES
WHERE OWNER = 'SIGEFER_APP'
  AND (
      INDEX_NAME LIKE 'IX_REP%'
      OR INDEX_NAME LIKE 'IX_HREP%'
      OR INDEX_NAME LIKE 'UQ_REP%'
      OR INDEX_NAME = 'IX_MOV_REPOSICION'
  )
ORDER BY INDEX_NAME;

SELECT
    VIEW_NAME
FROM ALL_VIEWS
WHERE OWNER = 'SIGEFER_APP'
  AND VIEW_NAME = 'VW_BPM_REPOSICION';

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME = 'MOVIMIENTO_INVENTARIO'
  AND COLUMN_NAME = 'ID_SOLICITUD_REPOSICION';

EXIT;
