ALTER SESSION SET CONTAINER = FREEPDB1;

SET ECHO ON
SET SQLBLANKLINES ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
SET VERIFY OFF
SET PAGESIZE 200
SET LINESIZE 260

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

PROMPT
PROMPT ============================================================
PROMPT SIGEFER - MODULO DE MONITOREO IOT
PROMPT ESP32 + DHT11 + MQTT
PROMPT ============================================================

PROMPT
PROMPT ============================================================
PROMPT 1. VERIFICACION DEL ESQUEMA
PROMPT ============================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM ALL_USERS
    WHERE USERNAME = 'SIGEFER_APP';

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20011,
            'No existe el esquema SIGEFER_APP'
        );
    END IF;

    DBMS_OUTPUT.PUT_LINE(
        'Esquema SIGEFER_APP verificado.'
    );
END;
/

PROMPT
PROMPT ============================================================
PROMPT 2. CREACION DE TABLAS E INDICES
PROMPT ============================================================

DECLARE
    PROCEDURE crear_tabla_si_falta(
        p_nombre VARCHAR2,
        p_ddl    VARCHAR2
    ) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM ALL_TABLES
        WHERE OWNER = 'SIGEFER_APP'
          AND TABLE_NAME = UPPER(p_nombre);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;

            DBMS_OUTPUT.PUT_LINE(
                'Tabla ' || UPPER(p_nombre) || ' creada.'
            );
        ELSE
            DBMS_OUTPUT.PUT_LINE(
                'Tabla ' || UPPER(p_nombre) || ' ya existe.'
            );
        END IF;
    END;

    PROCEDURE crear_indice_si_falta(
        p_nombre VARCHAR2,
        p_ddl    VARCHAR2
    ) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM ALL_INDEXES
        WHERE OWNER = 'SIGEFER_APP'
          AND INDEX_NAME = UPPER(p_nombre);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;

            DBMS_OUTPUT.PUT_LINE(
                'Indice ' || UPPER(p_nombre) || ' creado.'
            );
        ELSE
            DBMS_OUTPUT.PUT_LINE(
                'Indice ' || UPPER(p_nombre) || ' ya existe.'
            );
        END IF;
    END;
BEGIN
    crear_tabla_si_falta(
        'IOT_DISPOSITIVO',
        q'[
            CREATE TABLE SIGEFER_APP.IOT_DISPOSITIVO (
                ID_DISPOSITIVO NUMBER
                    GENERATED BY DEFAULT AS IDENTITY,

                CODIGO VARCHAR2(50) NOT NULL,
                NOMBRE VARCHAR2(150) NOT NULL,
                UBICACION VARCHAR2(200),

                TOPICO_TELEMETRIA VARCHAR2(200) NOT NULL,

                TIPO_SENSOR VARCHAR2(50)
                    DEFAULT 'ESP32_DHT11' NOT NULL,

                ESTADO CHAR(1)
                    DEFAULT 'A' NOT NULL,

                ULTIMA_COMUNICACION TIMESTAMP(6),
                ULTIMA_IP VARCHAR2(50),
                ULTIMO_RSSI_DBM NUMBER(4),
                ULTIMO_ESTADO_SENSOR VARCHAR2(30),

                FECHA_CREACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                FECHA_ACTUALIZACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                CONSTRAINT PK_IOT_DISPOSITIVO
                    PRIMARY KEY (ID_DISPOSITIVO),

                CONSTRAINT UQ_IOT_DISP_CODIGO
                    UNIQUE (CODIGO),

                CONSTRAINT UQ_IOT_DISP_TOPICO
                    UNIQUE (TOPICO_TELEMETRIA),

                CONSTRAINT CK_IOT_DISP_ESTADO
                    CHECK (ESTADO IN ('A', 'I')),

                CONSTRAINT CK_IOT_DISP_RSSI
                    CHECK (
                        ULTIMO_RSSI_DBM IS NULL
                        OR ULTIMO_RSSI_DBM
                            BETWEEN -150 AND 0
                    ),

                CONSTRAINT CKU_IOT_DISP_CODIGO
                    CHECK (
                        INSTR(
                            CODIGO,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_IOT_DISP_NOMBRE
                    CHECK (
                        INSTR(
                            NOMBRE,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_IOT_DISP_UBIC
                    CHECK (
                        UBICACION IS NULL
                        OR INSTR(
                            UBICACION,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_IOT_DISP_TOPICO
                    CHECK (
                        INSTR(
                            TOPICO_TELEMETRIA,
                            UNISTR('\FFFD')
                        ) = 0
                    )
            )
        ]'
    );

    crear_tabla_si_falta(
        'IOT_CONFIGURACION',
        q'[
            CREATE TABLE SIGEFER_APP.IOT_CONFIGURACION (
                ID_CONFIGURACION NUMBER
                    GENERATED BY DEFAULT AS IDENTITY,

                ID_DISPOSITIVO NUMBER NOT NULL,

                TEMPERATURA_MIN_C NUMBER(5,2)
                    DEFAULT 10 NOT NULL,

                TEMPERATURA_MAX_C NUMBER(5,2)
                    DEFAULT 30 NOT NULL,

                HUMEDAD_MIN_PCT NUMBER(5,2)
                    DEFAULT 25 NOT NULL,

                HUMEDAD_MAX_PCT NUMBER(5,2)
                    DEFAULT 70 NOT NULL,

                SEGUNDOS_SIN_COMUNICACION NUMBER(8)
                    DEFAULT 120 NOT NULL,

                ESTADO CHAR(1)
                    DEFAULT 'A' NOT NULL,

                FECHA_CREACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                FECHA_ACTUALIZACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                CONSTRAINT PK_IOT_CONFIGURACION
                    PRIMARY KEY (ID_CONFIGURACION),

                CONSTRAINT UQ_IOT_CONF_DISP
                    UNIQUE (ID_DISPOSITIVO),

                CONSTRAINT FK_IOT_CONF_DISP
                    FOREIGN KEY (ID_DISPOSITIVO)
                    REFERENCES SIGEFER_APP.IOT_DISPOSITIVO (
                        ID_DISPOSITIVO
                    ),

                CONSTRAINT CK_IOT_CONF_TEMP
                    CHECK (
                        TEMPERATURA_MIN_C <
                        TEMPERATURA_MAX_C
                    ),

                CONSTRAINT CK_IOT_CONF_HUM
                    CHECK (
                        HUMEDAD_MIN_PCT >= 0
                        AND HUMEDAD_MAX_PCT <= 100
                        AND HUMEDAD_MIN_PCT <
                            HUMEDAD_MAX_PCT
                    ),

                CONSTRAINT CK_IOT_CONF_SEG
                    CHECK (
                        SEGUNDOS_SIN_COMUNICACION > 0
                    ),

                CONSTRAINT CK_IOT_CONF_ESTADO
                    CHECK (ESTADO IN ('A', 'I'))
            )
        ]'
    );

    crear_tabla_si_falta(
        'IOT_LECTURA',
        q'[
            CREATE TABLE SIGEFER_APP.IOT_LECTURA (
                ID_LECTURA NUMBER
                    GENERATED BY DEFAULT AS IDENTITY,

                ID_DISPOSITIVO NUMBER NOT NULL,

                ID_ARRANQUE VARCHAR2(64) NOT NULL,
                SECUENCIA NUMBER(19) NOT NULL,

                TEMPERATURA_C NUMBER(5,2),
                HUMEDAD_PCT NUMBER(5,2),
                RSSI_DBM NUMBER(4),

                ESTADO_SENSOR VARCHAR2(30) NOT NULL,
                IP_DISPOSITIVO VARCHAR2(50),

                UPTIME_S NUMBER(19),
                LECTURAS_VALIDAS NUMBER(19),
                LECTURAS_FALLIDAS NUMBER(19),

                ORIGEN VARCHAR2(50) NOT NULL,
                PAYLOAD_JSON CLOB NOT NULL,

                FECHA_RECEPCION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                CONSTRAINT PK_IOT_LECTURA
                    PRIMARY KEY (ID_LECTURA),

                CONSTRAINT FK_IOT_LEC_DISP
                    FOREIGN KEY (ID_DISPOSITIVO)
                    REFERENCES SIGEFER_APP.IOT_DISPOSITIVO (
                        ID_DISPOSITIVO
                    ),

                CONSTRAINT UQ_IOT_LEC_UNICA
                    UNIQUE (
                        ID_DISPOSITIVO,
                        ID_ARRANQUE,
                        SECUENCIA
                    ),

                CONSTRAINT CK_IOT_LEC_SEQ
                    CHECK (SECUENCIA > 0),

                CONSTRAINT CK_IOT_LEC_TEMP
                    CHECK (
                        TEMPERATURA_C IS NULL
                        OR TEMPERATURA_C
                            BETWEEN -50 AND 100
                    ),

                CONSTRAINT CK_IOT_LEC_HUM
                    CHECK (
                        HUMEDAD_PCT IS NULL
                        OR HUMEDAD_PCT
                            BETWEEN 0 AND 100
                    ),

                CONSTRAINT CK_IOT_LEC_RSSI
                    CHECK (
                        RSSI_DBM IS NULL
                        OR RSSI_DBM
                            BETWEEN -150 AND 0
                    ),

                CONSTRAINT CK_IOT_LEC_SENSOR
                    CHECK (
                        ESTADO_SENSOR IN (
                            'OPERATIVO',
                            'ERROR_LECTURA'
                        )
                    ),

                CONSTRAINT CK_IOT_LEC_UPTIME
                    CHECK (
                        UPTIME_S IS NULL
                        OR UPTIME_S >= 0
                    ),

                CONSTRAINT CK_IOT_LEC_VALIDAS
                    CHECK (
                        LECTURAS_VALIDAS IS NULL
                        OR LECTURAS_VALIDAS >= 0
                    ),

                CONSTRAINT CK_IOT_LEC_FALLIDAS
                    CHECK (
                        LECTURAS_FALLIDAS IS NULL
                        OR LECTURAS_FALLIDAS >= 0
                    ),

                CONSTRAINT CKU_IOT_LEC_ARRANQUE
                    CHECK (
                        INSTR(
                            ID_ARRANQUE,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_IOT_LEC_SENSOR
                    CHECK (
                        INSTR(
                            ESTADO_SENSOR,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_IOT_LEC_IP
                    CHECK (
                        IP_DISPOSITIVO IS NULL
                        OR INSTR(
                            IP_DISPOSITIVO,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_IOT_LEC_ORIGEN
                    CHECK (
                        INSTR(
                            ORIGEN,
                            UNISTR('\FFFD')
                        ) = 0
                    )
            )
        ]'
    );

    crear_tabla_si_falta(
        'IOT_ALERTA',
        q'[
            CREATE TABLE SIGEFER_APP.IOT_ALERTA (
                ID_ALERTA_IOT NUMBER
                    GENERATED BY DEFAULT AS IDENTITY,

                ID_DISPOSITIVO NUMBER NOT NULL,
                ID_LECTURA NUMBER,

                TIPO_ALERTA VARCHAR2(30) NOT NULL,
                SEVERIDAD VARCHAR2(15) NOT NULL,
                MENSAJE VARCHAR2(1000) NOT NULL,

                VALOR_DETECTADO NUMBER(10,2),
                VALOR_LIMITE NUMBER(10,2),

                ESTADO VARCHAR2(12)
                    DEFAULT 'PENDIENTE' NOT NULL,

                FECHA_GENERACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                ID_USUARIO_ATENCION NUMBER,
                FECHA_ATENCION TIMESTAMP(6),
                OBSERVACION_ATENCION VARCHAR2(500),

                FECHA_ACTUALIZACION TIMESTAMP(6)
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                CONSTRAINT PK_IOT_ALERTA
                    PRIMARY KEY (ID_ALERTA_IOT),

                CONSTRAINT FK_IOT_ALERTA_DISP
                    FOREIGN KEY (ID_DISPOSITIVO)
                    REFERENCES SIGEFER_APP.IOT_DISPOSITIVO (
                        ID_DISPOSITIVO
                    ),

                CONSTRAINT FK_IOT_ALERTA_LECT
                    FOREIGN KEY (ID_LECTURA)
                    REFERENCES SIGEFER_APP.IOT_LECTURA (
                        ID_LECTURA
                    ),

                CONSTRAINT FK_IOT_ALERTA_USU
                    FOREIGN KEY (ID_USUARIO_ATENCION)
                    REFERENCES SIGEFER_APP.USUARIO (
                        ID_USUARIO
                    ),

                CONSTRAINT CK_IOT_ALERTA_TIPO
                    CHECK (
                        TIPO_ALERTA IN (
                            'TEMPERATURA_ALTA',
                            'TEMPERATURA_BAJA',
                            'HUMEDAD_ALTA',
                            'HUMEDAD_BAJA',
                            'ERROR_SENSOR',
                            'SIN_COMUNICACION'
                        )
                    ),

                CONSTRAINT CK_IOT_ALERTA_SEV
                    CHECK (
                        SEVERIDAD IN (
                            'INFORMATIVA',
                            'ADVERTENCIA',
                            'CRITICA'
                        )
                    ),

                CONSTRAINT CK_IOT_ALERTA_EST
                    CHECK (
                        ESTADO IN (
                            'PENDIENTE',
                            'ATENDIDA',
                            'DESCARTADA'
                        )
                    ),

                CONSTRAINT CK_IOT_ALERTA_FECHA
                    CHECK (
                        (
                            ESTADO = 'PENDIENTE'
                            AND FECHA_ATENCION IS NULL
                            AND ID_USUARIO_ATENCION IS NULL
                        )
                        OR
                        (
                            ESTADO IN (
                                'ATENDIDA',
                                'DESCARTADA'
                            )
                            AND FECHA_ATENCION IS NOT NULL
                            AND ID_USUARIO_ATENCION
                                IS NOT NULL
                        )
                    ),

                CONSTRAINT CKU_IOT_ALERTA_TIPO
                    CHECK (
                        INSTR(
                            TIPO_ALERTA,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_IOT_ALERTA_MENSAJE
                    CHECK (
                        INSTR(
                            MENSAJE,
                            UNISTR('\FFFD')
                        ) = 0
                    ),

                CONSTRAINT CKU_IOT_ALERTA_OBS
                    CHECK (
                        OBSERVACION_ATENCION IS NULL
                        OR INSTR(
                            OBSERVACION_ATENCION,
                            UNISTR('\FFFD')
                        ) = 0
                    )
            )
        ]'
    );

    crear_indice_si_falta(
        'IX_IOT_DISP_ULT_COM',
        q'[
            CREATE INDEX SIGEFER_APP.IX_IOT_DISP_ULT_COM
            ON SIGEFER_APP.IOT_DISPOSITIVO (
                ULTIMA_COMUNICACION
            )
        ]'
    );

    crear_indice_si_falta(
        'IX_IOT_LEC_DISP_FECHA',
        q'[
            CREATE INDEX SIGEFER_APP.IX_IOT_LEC_DISP_FECHA
            ON SIGEFER_APP.IOT_LECTURA (
                ID_DISPOSITIVO,
                FECHA_RECEPCION DESC
            )
        ]'
    );

    crear_indice_si_falta(
        'IX_IOT_ALERTA_EST_FECHA',
        q'[
            CREATE INDEX SIGEFER_APP.IX_IOT_ALERTA_EST_FECHA
            ON SIGEFER_APP.IOT_ALERTA (
                ESTADO,
                FECHA_GENERACION DESC
            )
        ]'
    );

    crear_indice_si_falta(
        'IX_IOT_ALERTA_DISP',
        q'[
            CREATE INDEX SIGEFER_APP.IX_IOT_ALERTA_DISP
            ON SIGEFER_APP.IOT_ALERTA (
                ID_DISPOSITIVO,
                TIPO_ALERTA,
                ESTADO
            )
        ]'
    );

    crear_indice_si_falta(
        'UQ_IOT_ALERTA_PEND',
        q'[
            CREATE UNIQUE INDEX
                SIGEFER_APP.UQ_IOT_ALERTA_PEND
            ON SIGEFER_APP.IOT_ALERTA (
                CASE
                    WHEN ESTADO = 'PENDIENTE'
                    THEN ID_DISPOSITIVO
                END,
                CASE
                    WHEN ESTADO = 'PENDIENTE'
                    THEN TIPO_ALERTA
                END
            )
        ]'
    );
END;
/

PROMPT
PROMPT ============================================================
PROMPT 3. COMENTARIOS
PROMPT ============================================================

COMMENT ON TABLE SIGEFER_APP.IOT_DISPOSITIVO IS
'Dispositivos físicos autorizados para publicar telemetría en SIGEFER';

COMMENT ON TABLE SIGEFER_APP.IOT_CONFIGURACION IS
'Umbrales ambientales y tiempo máximo sin comunicación por dispositivo';

COMMENT ON TABLE SIGEFER_APP.IOT_LECTURA IS
'Lecturas ambientales recibidas mediante MQTT desde dispositivos IoT';

COMMENT ON TABLE SIGEFER_APP.IOT_ALERTA IS
'Alertas ambientales o de comunicación generadas por el módulo IoT';

COMMENT ON COLUMN SIGEFER_APP.IOT_LECTURA.ID_ARRANQUE IS
'Identificador único generado por el ESP32 en cada reinicio';

COMMENT ON COLUMN SIGEFER_APP.IOT_LECTURA.PAYLOAD_JSON IS
'Mensaje MQTT original conservado para auditoría y diagnóstico';

COMMENT ON COLUMN SIGEFER_APP.IOT_DISPOSITIVO.ESTADO IS
'A = Activo, I = Inactivo';

PROMPT
PROMPT ============================================================
PROMPT 4. DISPOSITIVO Y CONFIGURACION INICIAL
PROMPT ============================================================

MERGE INTO SIGEFER_APP.IOT_DISPOSITIVO destino
USING (
    SELECT
        'BODEGA-01' AS CODIGO
    FROM DUAL
) origen
ON (
    destino.CODIGO = origen.CODIGO
)
WHEN NOT MATCHED THEN
    INSERT (
        CODIGO,
        NOMBRE,
        UBICACION,
        TOPICO_TELEMETRIA,
        TIPO_SENSOR,
        ESTADO
    )
    VALUES (
        'BODEGA-01',
        'Sensor ambiental de bodega',
        'BODEGA PRINCIPAL',
        'sigefer/iot/bodega-01/telemetria',
        'ESP32_DHT11',
        'A'
    );

MERGE INTO SIGEFER_APP.IOT_CONFIGURACION destino
USING (
    SELECT
        ID_DISPOSITIVO
    FROM SIGEFER_APP.IOT_DISPOSITIVO
    WHERE CODIGO = 'BODEGA-01'
) origen
ON (
    destino.ID_DISPOSITIVO =
        origen.ID_DISPOSITIVO
)
WHEN NOT MATCHED THEN
    INSERT (
        ID_DISPOSITIVO,
        TEMPERATURA_MIN_C,
        TEMPERATURA_MAX_C,
        HUMEDAD_MIN_PCT,
        HUMEDAD_MAX_PCT,
        SEGUNDOS_SIN_COMUNICACION,
        ESTADO
    )
    VALUES (
        origen.ID_DISPOSITIVO,
        10,
        30,
        25,
        70,
        120,
        'A'
    );

COMMIT;

PROMPT
PROMPT ============================================================
PROMPT 5. VERIFICACION
PROMPT ============================================================

COLUMN TABLE_NAME FORMAT A30
COLUMN CONSTRAINT_NAME FORMAT A30
COLUMN INDEX_NAME FORMAT A30
COLUMN CODIGO FORMAT A15
COLUMN NOMBRE FORMAT A35
COLUMN TOPICO_TELEMETRIA FORMAT A45

SELECT
    TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME LIKE 'IOT_%'
ORDER BY TABLE_NAME;

SELECT
    TABLE_NAME,
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    STATUS
FROM ALL_CONSTRAINTS
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME LIKE 'IOT_%'
ORDER BY
    TABLE_NAME,
    CONSTRAINT_NAME;

SELECT
    TABLE_NAME,
    INDEX_NAME,
    UNIQUENESS,
    STATUS
FROM ALL_INDEXES
WHERE OWNER = 'SIGEFER_APP'
  AND TABLE_NAME LIKE 'IOT_%'
ORDER BY
    TABLE_NAME,
    INDEX_NAME;

SELECT
    ID_DISPOSITIVO,
    CODIGO,
    NOMBRE,
    TOPICO_TELEMETRIA,
    TIPO_SENSOR,
    ESTADO
FROM SIGEFER_APP.IOT_DISPOSITIVO
WHERE CODIGO = 'BODEGA-01';

SELECT
    configuracion.ID_CONFIGURACION,
    dispositivo.CODIGO,
    configuracion.TEMPERATURA_MIN_C,
    configuracion.TEMPERATURA_MAX_C,
    configuracion.HUMEDAD_MIN_PCT,
    configuracion.HUMEDAD_MAX_PCT,
    configuracion.SEGUNDOS_SIN_COMUNICACION,
    configuracion.ESTADO
FROM SIGEFER_APP.IOT_CONFIGURACION configuracion
INNER JOIN SIGEFER_APP.IOT_DISPOSITIVO dispositivo
    ON dispositivo.ID_DISPOSITIVO =
        configuracion.ID_DISPOSITIVO
WHERE dispositivo.CODIGO = 'BODEGA-01';

PROMPT
PROMPT ============================================================
PROMPT MODULO IOT CREADO CORRECTAMENTE
PROMPT ============================================================

EXIT SUCCESS
